POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVyaWNwYXN0QGVyY2dkZy5kc2hmIiwiaWQiOjEsImlhdCI6MTY4MTIwODU3M30.dONOaOA35d8gTEsYlamGPAKthg7bfdEJugYrvcp5wE0
 
 {   
    "title": "More blogs 8",
    "author": "Er Testing",
    "url": "https://creating8/"
  }

