DELETE  http://localhost:3001/api/logout
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcml4QGxvcC5hbCIsImlkIjoyLCJpYXQiOjE2ODEzODM5NTF9.1_WAIn61rB7o0xzlggrGRXPeNwSo81NdbxhN2N6hxtg    